---
- name: Install nfs
  ansible.builtin.apt:
    update_cache: true
    name: "nfs-common"
    state: present
  when: ansible_os_family == "Debian"

- name: Install nfs
  ansible.builtin.yum:
    name: "nfs-utils"
    state: present
    update_cache: yes
  when: ansible_os_family == "RedHat"
